### ISSUE TITLE
Reason why API 23+ only

### ISSUE THREAD

**Issue by G00fY2** [saket/FluidKeyboardResize#11]
Hi Saket,

thanks for sharing your awesome solution. I just like to understand why the implementation does not work on Lollipop (< API 23) devices. Is it because of limitations of the _viewTreeObserver_ or because we can't reliably setup the _ActivityViewHolder_?

**Comment by saket** [comment]
No reason actually. This isn't a library so I did not care.

**Comment by G00fY2** [comment]
Okay, but I can't make it work on Lollipop devices. Lint also doesn't warn me about any APIs not available at this level. So I am wonderings what the reason could be. Did you try it on 5.1?

**Comment by saket** [comment]
What issue are you seeing? It might be helpful to check layout inspector to see what view is getting resized when the soft keyboard shows up.

**Comment by G00fY2** [comment]
In one of our apps the resize animation does not work on Lollipop. But I will further investigate the cause.
I just saw 7c7f318c7675d723180110c3064543a77d60c8ef and thought there might be a general limitation. Will report what the issue was.

Thanks for replying so quickly!

**Comment by saket** [comment]
I'm assuming you figured out the problem? Feel free to reopen otherwise.
