### ISSUE TITLE
Java Version?

### ISSUE THREAD

**Issue by khawarraza-netsoltech** [saket/FluidKeyboardResize#4]
Can I get a Java version of this project?

**Comment by saket** [comment]
This is just a sample project for my blog post and i won't be able to spend anymore effort on this except for bug fixes. What's stopping you from adding kotlin to your project?

**Comment by khawarraza-netsoltech** [comment]
Actually I have an old app written in Java. I just don't want to configure Kotlin for single library.

**Comment by saket** [comment]
In that case, feel free to convert this project to java for your usecase. You can start [here](https://github.com/saket/FluidKeyboardResize/blob/master/sample/src/main/java/me/saket/fluidresize/sample/FluidContentResizer.kt).

**Comment by midaslefkowitz** [comment]
@saket I created a branch with a java version but Im getting a 403 when I try to push. Any idea why?

**Comment by saket** [comment]
@midaslefkowitz what's the error message? There can be multiple reasons why Github is refusing with a 403.

**Comment by midaslefkowitz** [comment]
fatal: unable to access 'https://github.com/saket/FluidKeyboardResize.git/': The requested URL returned error: 403

Sorry, this is my first contribution to an open source github library...

**Comment by saket** [comment]
Oh that's simple. You're trying to push to my repository which you don't have write access to. I'm assuming you cloned my repository instead of yours so you'll have to replace the `remote` of your local git repository with your fork:

    git remote remove origin
    git remote add origin https://github.com/midaslefkowitz/FluidKeyboardResize.git/

You can only push to my repository if you're added as a collaborator. :)

**Comment by saket** [comment]
@khawarraza-netsoltech and others who're looking for a Java variant, you can use @midaslefkowitz's fork:

https://github.com/midaslefkowitz/FluidKeyboardResize/tree/java

**Comment by khawarraza-netsoltech** [comment]
Thanks. You saved my few hours  :)
