### ISSUE TITLE
Please add the Java version, too

### ISSUE THREAD

**Issue by nuhkoca** [saket/FluidKeyboardResize#7]
Hi @saket,

Thanks for such a great sample about how to adjust content according to keyboard status. We really need this logic in our projects but we use Java at the office, not Kotlin. Could you please create the Java one for this? If so, it would be great. I know it may take a very short time.

Thanks in advance!

**Comment by midaslefkowitz** [comment]
Hi @nuhkoca,

You can check out my java fork [here](https://github.com/midaslefkowitz/FluidKeyboardResize/tree/java)

**Comment by nuhkoca** [comment]
Hi @midaslefkowitz,

You are just great bro! Thanks a lot! It works like a charm!

Have a nice day!
